id: AA850A67D
title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:18:41.361434
  last_modified_at: 2022-03-01 01:18:41.361442
